project_name: bin-vendor

snapshot:
  name_template: "{{ .ShortCommit }}"

builds:
  - id: bin-vendor
    main: ./cmd/bin-vendor/main.go
    binary: bin-vendor
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64
