name: "bin-vendor"
description: "Download and manage project dependent toolchains."
inputs:
  version:
    description: "Specify the version of bin-vendor to use"
    default: "v0.0.3"
    required: false
  config:
    description: "Where the configuration is located."
    default: "bin.yaml"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup bin-vendor
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        mkdir ${HOME}/bin-vendor
        pushd ${HOME}/bin-vendor
        curl -sSLo bin-vendor.tar.gz https://github.com/mjpitz/bin-vendor/releases/download/${VERSION}/bin-vendor_${VERSION##v}_linux_amd64.tar.gz
        tar zxf bin-vendor.tar.gz
        sudo mv ./bin-vendor /usr/local/bin/bin-vendor
        ls -la /usr/local/bin/bin-vendor
        popd
        rm -rf ${HOME}/bin-vendor

    - name: Vendor binaries
      shell: bash
      run: |
        bin-vendor -config ${{ inputs.config }}
